apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-service-app
  labels:
    app: webinar-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webinar-service-app
  template:
    metadata:
      labels:
        app: webinar-service-app
    spec:
      containers:
        - name: webinar-service-app
          image: rg299299/webinar
          imagePullPolicy: Always
          ports:
            - containerPort: 2222

---
apiVersion: v1
kind: Service
metadata:
  name: webinar-service-svc
spec:
  ports:
    - targetPort: 2222
      port: 80
  selector:
    app: webinar-service-app